allowBuilds:
  '@clerk/shared': true
  '@tailwindcss/oxide': true
  canvas: true
  core-js: true
  core-js-pure: true
  esbuild: true
  puppeteer: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - '@clerk/shared'
  - '@tailwindcss/oxide'
  - canvas
  - esbuild
  - sharp

onlyBuiltDependencies:
  - puppeteer
