allowBuilds:
  '@clerk/shared': true
  '@tailwindcss/oxide': true
  canvas: true
  core-js: true
  core-js-pure: true
  esbuild: true
  puppeteer: true
  sharp: true
  unrs-resolver: true

overrides:
  '@types/react': 19.2.0
  '@types/react-dom': 19.2.0

ignoredBuiltDependencies:
  - '@clerk/shared'
  - '@tailwindcss/oxide'
  - canvas
  - core-js-pure
  - esbuild
  - sharp

onlyBuiltDependencies:
  - core-js
  - puppeteer
