import { ThemeProvider } from "@/components/theme-provider"
import type { Metadata } from "next";
import { Toaster } from "sonner"
import "./globals.css";
import "./loading";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar";
import { ClerkProvider, SignedIn } from '@clerk/nextjs';
import { Footer } from "@/components/footer";
import WebPushManager from "@/components/WebPushManager";
import { NotificationProvider } from "@/contexts/NotificationContext";

export const metadata: Metadata = {
  title: "Khadim-Millat Welfare Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NotificationProvider>
              <SidebarProvider>
                <AppSidebar />
                <SidebarInset>
                  <main className="min-h-screen">
                    <SidebarTrigger className="fixed top-0 z-50" />
                    <WebPushManager />
                    {children}
                    <Toaster richColors closeButton />
                  </main>
                  <Footer />
                </SidebarInset>
              </SidebarProvider>
            </NotificationProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
