import { ThemeProvider } from "@/components/theme-provider"
import type { Metadata } from "next";
import { Toaster } from "sonner"
import "./globals.css";
import "./loading";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar";
import { ClerkProvider, SignedIn } from '@clerk/nextjs';
import { Footer } from "@/components/footer";

export const metadata: Metadata = {
  title: "Khadim-Millat Welfare Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          > <SidebarProvider>
              <AppSidebar />
              <SidebarInset>
                <main className="min-h-screen">
                  {/* Sidebar trigger placed in document flow near top-left with minor margin */}
                  <div className="p-2">
                    <SidebarTrigger />
                  </div>
                  <div className="pt-2">{children}</div>
                  <Toaster richColors closeButton />
                </main>
                <Footer />
              </SidebarInset>
            </SidebarProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
